name: run-tests
on:
  push:
    branch: [master]

jobs:
  run-jest:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - run: npm install --save-dev jest
      - run: npm run test 